openapi: 3.0.1
info:
  version: 1.0.0
  title: Spring Design Pattern
  description: Spring Design Pattern
  termsOfService: http://swagger.io/terms/
  contact:
    name: Osman KUSTU
    url: http://swagger.io
    email: Osmankustu@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /v3/payment:
    post:
      tags:
        - Payment
      summary: Make payment with generated api
      operationId: payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        orderId:
          type: string
        paymentType:
          type: string
        amount:
          type: double
      required:
        - orderId
        - paymentType
        - amount
      example:
        orderId: 123
        paymentType: creditCard
        amount: 123.5